### ISSUE TITLE
No Kubernetes container liveness probe defined for Ingress Controller sidecar containers

### ISSUE THREAD

**Issue by chirangaalwis** [wallarm/ingress#222]
### Description
$subject noted for sidecars of Wallarm Ingress Controller added when `controller.wallarm.enabled` is set to true - `cron`, `collectd` and `synccloud`.

Container definitions [hard coded under chart helper functions](https://github.com/wallarm/ingress/blob/main/charts/ingress-nginx/templates/_helpers.tpl).

Violation of Kubernetes policy - [https://docs.bridgecrew.io/docs/bc_k8s_7](https://docs.bridgecrew.io/docs/bc_k8s_7)

**Comment by xDmitriev** [comment]
Thank you for pointing it out. There is no liveness probe for helper containers by design.

**Comment by chirangaalwis** [comment]
@xDmitriev but containers `cron`, `collectd` and `synccloud` are long running side car containers, aren't they?

Hence, it is a best practice to keep track of their health. Currently, there is no indication of whether they are in a broken state or not.

**Comment by xDmitriev** [comment]
Yes, they are long-running containers. The primary rationale behind the absence of health checks is that these helper containers are essential for the proper operation of Wallarm functionality. In the event that this functionality malfunctions due to any reason, restarting the entire pod would be impractical as it would cause traffic disruption.

**Comment by xDmitriev** [comment]
By the way, we are working on a better implementation of helpers. Eventually, it will be one binary that serves all functions (init, sync, corn, etc), which means that we will have only 2 additional containers - init and helper.

**Comment by DilanUA** [comment]
> Yes, they are long-running containers. The primary rationale behind the absence of health checks is that these helper containers are essential for the proper operation of Wallarm functionality. In the event that this functionality malfunctions due to any reason, restarting the entire pod would be impractical as it would cause traffic disruption.

@xDmitriev If setting up a liveness probe becomes a reason for traffic disruption, there has to be a problem in Wallarm design. If there is indeed an issue inside a helper pod and if an automatic restart is helpful in quick recovery, a liveness probe is a better way to achieve it. And restarting one pod in case of failure should not cause traffic disruption if multiple replicas are maintained to achieve high availability.

**Comment by xDmitriev** [comment]
> If setting up a liveness probe becomes a reason for traffic disruption, there has to be a problem in Wallarm design.
If the liveness probe failed for one container then the whole Pod will be restarted, it's by Kubernetes design 

> If there is indeed an issue inside a helper pod and if an automatic restart is helpful in quick recovery, a liveness probe is a better way to achieve it.
If the automatic restart does not help, then the whole Pod will restart continuously.
 
>And restarting one pod in case of failure should not cause traffic disruption if multiple replicas are maintained to achieve high availability.

-  It will cause traffic disruption because all established connections will not be drained gracefully as they do during the rolling upgrade
- We do not know is there HA configured or not, there can be any case

The main point is that if Walalrm functionality is broken for any reason (helpers or whatever), which is ultimately a very rare case,  it is not acceptable to disrupt the traffic which goes via Ingress
