### ISSUE TITLE
Introduce option to mount Wallarm API token Kubernetes Secret as a file

### ISSUE THREAD

**Issue by chirangaalwis** [wallarm/ingress#232]
### Description
As per the recommendation under Kubernetes Policy [CKV_K8S_35](https://docs.bridgecrew.io/docs/bc_k8s_33), $subject would help us avoid [introducing Secret values via environment variables to Wallarm containers](https://github.com/wallarm/ingress/blob/4.6.2+upstream4.6.0/charts/ingress-nginx/templates/_helpers.tpl#L202-L213).

**Comment by xDmitriev** [comment]
The mentioned subject has low severity. Could you tell me for what specific reason you want to avoid using env var? Which goal do you want to achieve by using volume over env var?

**Comment by DilanUA** [comment]
@xDmitriev 

> The mentioned subject has low severity. Could you tell me for what specific reason you want to avoid using env var? Which goal do you want to achieve by using volume over env var?

Storing credentials in environment variables (envs) within a Kubernetes container can have potential security risks for the following reasons:

Process Visibility: Environment variables are visible to all processes running within the container. Any process with sufficient privileges can access and read the environment variables, potentially exposing sensitive information, including credentials. This could be an issue if an attacker gains unauthorized access to the container or if there are malicious processes running inside the container.

Container Inspection: If credentials are stored in envs, they can be exposed inadvertently or intentionally, 
compromising the security of the system.

Container Snapshots: Containers can be snapshotted or checkpointed for various purposes, such as backup or migration. These snapshots may include environment variables, including credentials. If the snapshots are not handled securely or are accessible by unauthorized individuals, the credentials could be exposed.

Logging and Monitoring: Environment variables can be logged and monitored by container orchestration systems, logging solutions, or other monitoring tools. This means that credentials stored in envs might end up in log files, which can be a security risk if the logs are not adequately protected or if they are accessed by unauthorized individuals.

Configuration Leakage: It's possible for the environment variables to be inadvertently exposed in application logs, error messages, or other forms of output. This can happen if the application is misconfigured, leading to sensitive information, such as credentials, being leaked outside the container.

Hence it is a security-best-practice to mount them as files rather than via ENVs in order to avoid above scenarios and achieve better security. Please reopen the ticket as we would like to consider this as an issue with high priority, considering the security of Wallarm API tokens.
